ModusCreateOrg/app-med-ai-gen

.husky/pre-commit, .husky/pre-push, lizard.sh
This PR introduces a comprehensive set of Git hooks and code quality tools to improve our development workflow and maintain high code quality standards across the project.
- Added a pre-commit hook to run automated checks before each commit.
- Implemented linting for JavaScript/TypeScript files.
- Improvements in how the pre-commit and pre-push works.
=> Git Hooks and Code Quality Tools Improvement

.cursor/rules/aws-amplify-best-practices.mdc, .cursor/rules/axios-best-practices.mdc, .cursor/rules/capacitor-best-practices.mdc, .cursor/rules/formik-best-practices.mdc, .cursor/rules/general.mdc, .cursor/rules/ionic-best-practices.mdc, .cursor/rules/react-best-practices.mdc, .cursor/rules/react-router-best-practices.mdc, .cursor/rules/typescript-best-practices.mdc, .cursorrules, frontend/src/common/components/Input/CheckboxInput.scss, frontend/src/common/utils/i18n/resources/en/auth.json, frontend/src/common/utils/i18n/resources/en/common.json, frontend/src/common/utils/i18n/resources/es/auth.json, frontend/src/common/utils/i18n/resources/es/common.json, frontend/src/common/utils/i18n/resources/fr/auth.json, frontend/src/common/utils/i18n/resources/fr/common.json, frontend/src/pages/Auth/SignIn/SignInPage.scss, frontend/src/pages/Auth/SignIn/SignInPage.tsx, frontend/src/pages/Auth/SignIn/components/SignInForm.scss, frontend/src/pages/Auth/SignIn/components/SignInForm.tsx, memory-bank/activeContext.md, memory-bank/productContext.md, memory-bank/progress.md, memory-bank/projectbrief.md, memory-bank/systemPatterns.md, memory-bank/techContext.md
- **UI Redesign**: Completely redesigned the Sign In page to match Figma designs
- Implemented dark blue background with white card layout
- Added logo and "MEDReport AI" text in proper position
- Adjusted typography, spacing and colors to match design specs
- Improved form input styling with proper heights and border radius
- **UX Improvements**:
- Fixed checkbox positioning in "Remember me" option
- Adjusted font sizes for better readability
- Temporarily removed social login buttons
- Improved spacing between elements
- **Internationalization**:
- Added proper i18n translations for all UI text
- Added new translation keys to English, Spanish, and French files
- Created code rule for consistent text handling
- Updated memory-bank documentation with i18n guidelines
No. All existing …
=> [NO-TICKET] - Cursor improvements

backend/README.md, backend/package-lock.json, backend/package.json, backend/src/iac/backend-stack.ts, backend/src/iac/deploy.sh, backend/src/iac/update-api-policy.js
Create API Gateway
Create all the necessary resources
Add resource policy with a deploy script
{...}
{...}
{...}
=> Ade 150 api configuration

frontend/src/pages/Chat/ChatPage.scss
- Remove unnecessary height calculation from ChatPage styles to ensure proper scrolling behavior.
=> [ADE-166] - Remove unnecessary height calculation from ChatPage styles to ensure proper scrolling behavior.

frontend/src/common/services/ai/bedrock.service.ts, frontend/src/common/utils/i18n/index.ts, frontend/src/common/utils/i18n/resources/en/errors.json, frontend/src/common/utils/i18n/resources/en/index.ts, frontend/src/common/utils/i18n/resources/es/errors.json, frontend/src/common/utils/i18n/resources/es/index.ts, frontend/src/common/utils/i18n/resources/fr/errors.json, frontend/src/common/utils/i18n/resources/fr/index.ts, frontend/src/pages/Chat/ChatPage.tsx
- Added CONTENT_FILTERED_MESSAGE constant to provide user-friendly feedback when responses are filtered.
- Implemented handleBedrockResponse method in BedrockService to manage content filtering and log filtered responses for analytics.
- Updated invokeModel method to utilize the new response handling logic.
- Improved error handling in ChatPage by creating a user-friendly error message when AI response fails.
=> [ADE-166] - Enhance Bedrock service and ChatPage error handling

backend/src/app.module.ts
exclude document-processor routes from auth middleware
{...}
{...}
{...}
=> [ADE-152] exclude document-processor routes from auth middleware

backend/src/iac/backend-stack.ts, backend/src/iac/cdk.index.ts
- Use SSM Parameter Store to get Cognito client credentials
{...}
{...}
{...}
=> Fix GitHub workflow

.github/workflows/deploy-development.yml, backend/src/iac/backend-stack.ts
- Update aws-cdk to fix error https://github.com/ModusCreateOrg/app-med-ai-gen/actions/runs/14378979347/job/40318064673
- Update the SSM parameter name call
{...}
{...}
{...}
=> Fix deployment error

backend/src/iac/backend-stack.ts
- Add POST method to API Gateway
{...}
{...}
{...}
=> Add POST /api/reports to the API Gateway

frontend/src/common/components/Router/TabNavigation.tsx, frontend/src/common/components/Router/__tests__/TabNavigation.test.tsx
Add link to reports page
{...}
{...}
{...}
=> ADE-35 Add link to reports page

backend/src/document-processor/controllers/document-processor.controller.ts, backend/src/iac/backend-stack.ts
Rename GSI from 'userIdDateIndex' to 'userIdCreatedAtIndex' for clarity
{...}
{...}
{...}
=> Rename GSI from 'userIdDateIndex' to 'userIdCreatedAtIndex' for clarity

backend/src/iac/backend-stack.ts
Add document processor resource and POST method for file processing
{...}
{...}
{...}
=> Add document processor resource and POST method for file processing

frontend/src/common/components/Upload/UploadModal.scss
Adjust margin for cancel notice to align with design specifications
{...}
{...}
{...}
=> Adjust margin for cancel notice to align with design specifications

frontend/src/common/components/Upload/UploadModal.scss
fix: Adjust margins for file limits and upload button in UploadModal
{...}
{...}
{...}
=> [ADE-60] fix: Adjust margins for file limits and upload button in UploadModal

backend/src/reports/reports.service.ts
Fix bug on bookmark endpont.
{...}
{...}
{...}
=> Add userId to ConditionExpression query

frontend/src/pages/Home/HomePage.tsx
Show bookmarks on the home page
{...}
{...}
{...}
=> Show bookmarks on the home page

backend/src/iac/backend-stack.ts
Add permission to read Perplexity API key from Secrets Manager
{...}
{...}
{...}
=> Add permission to read Perplexity API key from Secrets Manager

backend/src/reports/reports.service.ts
enhance report update with default values for missing fields and improved error handling
{...}
{...}
{...}
=> [ADE-66] enhance report update with default values for missing fields and improved error handling

backend/src/reports/reports.service.ts
fix: update isMedicalReport handling to correctly reflect boolean values
{...}
{...}
{...}
=> [ADE-66]  fix: update isMedicalReport handling to correctly reflect boolean values

frontend/src/pages/Reports/components/OriginalReportTab.tsx
Fix rendering of medical comments section in OriginalReportTab component
{...}
{...}
{...}
=> [ADE-208] Fix rendering of medical comments section in OriginalReportTab component

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json
chore: update dependencies for backend and frontend packages to latest versions
=> chore: update dependencies for backend and frontend packages to latest versions

frontend/src/common/utils/i18n/resources/en/report.json, frontend/src/common/utils/i18n/resources/en/reportDetail.json, frontend/src/common/utils/i18n/resources/es/report.json, frontend/src/common/utils/i18n/resources/es/reportDetail.json, frontend/src/common/utils/i18n/resources/fr/report.json, frontend/src/common/utils/i18n/resources/fr/reportDetail.json
feat: add icon and update low/high labels in report and reportDetail translations
=> feat: add icon and update low/high labels in report and reportDetail translations
