ModusCreateOrg/app-med-ai-gen

frontend/src/common/utils/auth-errors.ts
frontend/src/common/utils/i18n/resources/en/auth.json
frontend/src/pages/Auth/SignUp/SignUpPage.scss
frontend/src/pages/Auth/SignUp/SignUpPage.tsx
frontend/src/pages/Auth/SignUp/components/SignUpForm.scss
frontend/src/pages/Auth/SignUp/components/SignUpForm.tsx

Authentication issues -> https://moduscreate.atlassian.net/browse/ADE-137

[ADE-137] - Update auth error messages for clarity and improve email validation prompt

---

backend/src/app.module.ts
backend/src/auth/auth.middleware.ts
backend/src/iac/backend-stack.ts
backend/src/iac/update-api-policy.js
backend/src/main.ts
backend/src/reports/reports.controller.ts
backend/src/reports/reports.service.ts

- CORS pre-flight configuration.
- API Gateway response types.
- API Resource Policy.
{...}
{...}
{...}

ADE-35 - Fix CORS issues on Android

---

.husky/pre-push
frontend/src/common/services/ai/bedrock.service.ts

- Added a new healthcare-focused system prompt in BedrockService to guide AI responses.
- Updated invokeModel method to accept an optional system prompt, enhancing flexibility.
- Refactored response handling to accommodate Claude API responses instead of Bedrock.
- Removed dependency on husky.sh in the pre-push hook for improved script clarity.
{...}
{...}
{...}

[ADE-166] Answer only medical questions and use claude 3.7 sonnet

---

frontend/src/common/services/ai/bedrock.service.ts

- Introduced a new bedrockCredentials object to encapsulate AWS credentials, improving code readability and maintainability.
- Simplified the initialization of BedrockRuntimeClient by passing the new credentials object directly.
{...}
{...}
{...}

[ADE-152] Refactor BedrockService to streamline credential handling

---

frontend/src/pages/Home/components/ReportItem/__tests__/ReportItem.test.tsx
frontend/src/pages/Upload/__tests__/UploadPage.test.tsx

feat: Rename date field to createdAt in report mock data for consistency
{...}
{...}
{...}

feat: Rename date field to createdAt in report mock data for consistency

---

frontend/src/common/components/Upload/UploadModal.scss
frontend/src/common/components/Upload/UploadModal.tsx

{Describe what kind of change does this PR introduce}
This pull request introduces changes to the `UploadModal` component in the frontend to enhance the user experience by adding a cancel notice feature. The changes include updates to both the styles and the component logic to handle the display of the cancel notice.
* **Styling updates:**
* Added styles for the cancel notice to match the design specifications, including flex display, alignment, background color, padding, margin, border, and text styling in `UploadModal.scss`.
* **Component logic updates:**
* Introduced a new state `showCancelNotice` to track when to show the upload canceled notice in `UploadModal.tsx`.
* Updated the effect to hide the cancel notice when starting a new upload in `UploadModal.tsx`.
* Modified the …

feat: Add cancel notice functionality in UploadModal component

---

backend/src/reports/reports.service.ts

Bug fix for GET /reports/{reportId}
{...}
{...}
{...}

[No ticket] Fix GET report by id

---

backend/src/iac/backend-stack.ts
frontend/src/common/hooks/useTimeout.ts

followup to implementing the frontend of processing and showing the reports
{...}
{...}
{...}

[ADE-66] followup to implementing the frontend of processing and showing the reports

---

backend/src/iac/backend-stack.ts
backend/src/main.ts

feat: Add 5-minute timeout for API Gateway integration and server
{...}
{...}
{...}

feat: Add 5-minute timeout for API Gateway integration and server

---

backend/src/iac/backend-stack.ts
frontend/src/common/components/Icon/Icon.tsx
frontend/src/common/components/Router/TabNavigation.tsx
frontend/src/pages/Reports/ReportDetailPage.scss
frontend/src/pages/Reports/ReportDetailPage.tsx

This pull request introduces several changes to both the backend and frontend codebases. On the backend, a new API resource and method for retrieving report statuses has been added under the `document-processor` resource. On the frontend, new icons are added to the `Icon` component, and minor formatting adjustments are made to the `TabNavigation` component. Below is a breakdown of the most important changes:
* Added a new `report-status/{reportId}` resource under the `document-processor` API, including integration with an HTTP proxy to retrieve report statuses. (`backend/src/iac/backend-stack.ts`, [[1]](diffhunk://#diff-ff1f60c969d194b954acd9d1fff28cf3df571cfb093b8c7142d073178f7c55b2R403-R405) [[2]](diffhunk://#diff-ff1f60c969d194b954acd9d1fff28cf3df571cfb093b8c7142d073178f7c55b2R473-R485) …

[ADE-66] create ReportDetailPage & add report-status api gateway endpoint

---

frontend/src/pages/Processing/ProcessingPage.scss
frontend/src/pages/Processing/ProcessingPage.tsx
frontend/src/pages/Processing/components/ProcessingAnimation.tsx
frontend/src/pages/Processing/components/ProcessingError.tsx

This pull request enhances the `ProcessingPage` by introducing better error handling, modularizing components, and improving the user experience with animations and error states. Key changes include the addition of new components for error and animation handling, refactoring the status-checking logic, and updating the SCSS for styling.
* Added a new `ProcessingAnimation` component to encapsulate the animation and processing message. (`frontend/src/pages/Processing/components/ProcessingAnimation.tsx`)
* Added a new `ProcessingError` component to handle and display error states with retry and upload actions. (`frontend/src/pages/Processing/components/ProcessingError.tsx`)
* Refactored the status-checking logic to include a `clearStatusCheckInterval` function for better cleanup and error …

[ADE-66] Add error handling and animation components to ProcessingPage for improved user feedback

---

frontend/src/pages/Processing/ProcessingPage.tsx
package-lock.json

Refactor ProcessingPage component and update package-lock.json to include Prettier
{...}
{...}
{...}

Refactor ProcessingPage component and update package-lock.json to include Prettier

---

backend/src/services/perplexity.service.ts
frontend/src/common/components/AIAssistant/AIAssistantModal.scss
frontend/src/common/hooks/useFileUpload.ts
frontend/src/pages/Chat/__tests__/ChatPage.test.tsx
frontend/src/pages/Processing/ProcessingPage.scss
frontend/src/pages/Upload/__tests__/UploadPage.test.tsx

- style: Improve SCSS formatting for better readability in AIAssistantModal and ProcessingPage
- feat: Add additional mock data for UploadModal in UploadPage tests
- fix: Enhance system prompt clarity and user prompt constraints in explainMedicalText method
{...}
{...}
{...}

[ADE-66] Enhance system prompt clarity and user prompt constraints in explainMedicalText method

---

backend/src/reports/reports.controller.ts
backend/src/reports/reports.service.ts
backend/src/services/perplexity.service.ts
frontend/src/pages/Reports/components/ReportHeader.tsx

This pull request introduces several enhancements and fixes across the backend and frontend of the application. Key updates include improved error handling in the reports controller, enhanced filtering logic in the reports service, the addition of a new method to delete reports, and minor changes in the frontend and other services for better usability and consistency.
* Added `NotFoundException` to handle cases where a report is not found or its processing status is `FAILED` in the `getReport` method. [[1]](diffhunk://#diff-478dcda72a35ff7cb831da19848500fdb38b17db25b6770e818cbd37448bb449R12) [[2]](diffhunk://#diff-478dcda72a35ff7cb831da19848500fdb38b17db25b6770e818cbd37448bb449L83-R94)
* Enhanced filtering in the `findAll` and `findLatest` methods to optionally exclude reports with a …

[ADE-66] fix: Enhance report retrieval and deletion logic; update processing status checks and improve error handling

---

backend/PERPLEXITY_INTEGRATION.md
backend/src/config/configuration.ts
backend/src/iac/backend-stack.ts
backend/src/services/perplexity.service.ts

fix: Update Perplexity API key secret name across configuration files
{...}
{...}
{...}

fix: Update Perplexity API key secret name across configuration files

---

backend/src/iac/backend-stack.ts

Refactor IAM policy to allow access to Perplexity API key with wildcard for Secrets Manager
{...}
{...}
{...}

Refactor IAM policy to allow access to Perplexity API key with wildcard for Secrets Manager

---

backend/src/document-processor/controllers/document-processor.controller.ts
backend/src/iac/backend-stack.ts
backend/src/reports/reports.controller.ts
frontend/src/common/utils/i18n/resources/en/common.json
frontend/src/pages/Reports/ReportDetailPage.tsx
frontend/src/pages/Reports/components/AiAnalysisTab.tsx
frontend/src/pages/Upload/UploadPage.tsx

This pull request introduces several changes across the backend and frontend to enhance document processing, report management, and user experience. Key updates include improved handling of document processing states, the addition of a report deletion feature, and UI adjustments for better usability.
* Enhanced the `DocumentProcessorController` to provide more descriptive messages based on the processing status (`IN_PROGRESS`, `PROCESSED`, or not started) when initiating document processing. This ensures clearer feedback to users. [[1]](diffhunk://#diff-d447fd4ea0593ae5a76e621fc7bce2d97e41ec8981273a5c1db2ae765d303157R146-R154) [[2]](diffhunk://#diff-d447fd4ea0593ae5a76e621fc7bce2d97e41ec8981273a5c1db2ae765d303157R164-R170)
* Added a new `DELETE` endpoint in the `ReportsController` to …

[ADE-66] fixes and improvements to uploading, processing, and viewing a report

---

backend/src/document-processor/services/aws-bedrock.service.ts
backend/src/document-processor/services/document-processor.service.ts
backend/src/services/perplexity.service.ts

This pull request introduces significant enhancements to the medical document processing pipeline by incorporating verification against trusted medical sources and improving error handling. Key changes include adding a verification step using Perplexity AI, updating the analysis logic to handle missing reference ranges, and expanding the Perplexity service with a new method for reviewing medical analyses.
* Updated `aws-bedrock.service.ts` to include a list of trusted medical sources (e.g., Mayo Clinic, CDC, WHO) for analysis and to handle cases where reference ranges are missing by using standard ranges from these sources. (`[[1]](diffhunk://#diff-5c85186b48ca73f6f71ee9bca3b21941f8a85b0f18c47f20c0bb94dfddcbb0adR59-R70)`, `[[2]](diffhunk://#diff-5c85186b48ca73f6f71ee9bca3b21941f8a85b0f18c4 …

[ADE-66] Enhance medical document processing by adding trusted medical sources for analysis and other improvements

---

frontend/src/common/models/medicalReport.ts
frontend/src/common/utils/i18n/resources/en/reportDetail.json
frontend/src/common/utils/i18n/resources/es/report.json
frontend/src/common/utils/i18n/resources/fr/report.json
frontend/src/pages/Reports/components/AiAnalysisTab.tsx
frontend/src/pages/Reports/components/MissingReferenceRangesNotice.tsx

- Add ReportMetadata interface and internationalize missing reference ranges message in reports
- Introduced ReportMetadata interface in frontend/src/common/models/medicalReport.ts to encapsulate metadata related to medical reports.
- Added internationalized message for missing reference ranges in English, Spanish, and French translation files.
- Updated AiAnalysisTab component to display a notice when reference ranges are missing.
{...}
{...}
{...}

[ADE-66] Add ReportMetadata interface and internationalize missing reference ranges message in reports

---

backend/src/reports/reports.service.ts
frontend/src/common/api/__tests__/reportService.test.ts
frontend/src/common/api/reportService.ts

This pull request includes updates to the `ReportsService` in the backend and changes to the API endpoints and their usage in the frontend. The most important changes involve modifying the DynamoDB key structure in the backend and updating the API endpoint for marking reports as read in the frontend.
* Updated the `ReportsService` in `reports.service.ts` to use a composite key (`userId` as the partition key and `id` as the sort key) for DynamoDB operations, ensuring better data organization and query flexibility.
* Updated the API endpoint for marking reports as read by appending `/status` to the URL in `reportService.test.ts` and `reportService.ts`, aligning it with the new backend API structure. [[1]](diffhunk://#diff-bbd513a14ebe42d4142dd925ff9996c50a68483339680a30dc5029c0c17f5446L106-R …

Update reportService API endpoint for marking reports as read

---

backend/src/reports/reports.service.ts

- Enhance error handling in ReportsService for DynamoDB operations
- Added specific error handling for ValidationException and ProvisionedThroughputExceededException in multiple methods of ReportsService.
- Improved logging for validation errors and throughput issues, providing clearer feedback for report updates and bookmark toggling.
- Updated InternalServerErrorException messages to include more context about the errors encountered.
{...}
{...}
{...}

[ADE-66] Enhance error handling in ReportsService for DynamoDB operations

---

backend/src/document-processor/controllers/document-processor.controller.ts
backend/src/reports/models/report.model.ts
frontend/src/common/components/Input/__tests__/SelectInput.test.tsx
frontend/src/common/models/medicalReport.ts
frontend/src/pages/Reports/components/AiAnalysisTab.tsx
frontend/src/pages/Reports/components/EmergencyAlert.tsx

add missingInformation field to report model and update processing logic
{...}
{...}
{...}

[ADE-66] add missingInformation field to report model and update processing logic

---

backend/src/reports/reports.service.ts

fix showing 'reference-ranges-missing' notice
{...}
{...}
{...}

[ADE-66] fix showing 'reference-ranges-missing' notice

---

frontend/src/common/utils/i18n/resources/en/report.json
frontend/src/common/utils/i18n/resources/es/report.json
frontend/src/common/utils/i18n/resources/fr/report.json
frontend/src/pages/Reports/ReportsListPage.tsx
frontend/src/pages/Reports/components/FilterPanel/FilterPanel.scss
frontend/src/pages/Reports/components/ReportsFilterEmpty/ReportsFilterEmpty.scss
frontend/src/pages/Reports/components/ReportsFilterEmpty/ReportsFilterEmpty.tsx
frontend/src/pages/Reports/components/ReportsFilterEmpty/index.ts
frontend/src/types/custom.d.ts
frontend/tsconfig.json

Empty states in the filters
Change button colors
Update breakpoints.
{...}
{...}
{...}

ADE-200 Updates to the UI

---

frontend/src/setupTests.ts
frontend/src/types/vitest.d.ts

Refactor test setup: standardize scrollIntoView function formatting and add Vitest type definitions
{...}
{...}
{...}

Refactor test setup: standardize scrollIntoView function formatting and add Vitest type definitions

---

frontend/src/common/components/Modal/ConfirmationModal.scss
frontend/src/common/components/Modal/ConfirmationModal.tsx
frontend/src/common/utils/i18n/resources/en/common.json
frontend/src/common/utils/i18n/resources/es/common.json
frontend/src/common/utils/i18n/resources/fr/common.json
frontend/src/pages/Reports/ReportDetailPage.tsx
frontend/src/pages/Reports/components/ActionButtons.tsx

This pull request introduces a reusable `ConfirmationModal` component for confirmation dialogs, integrates it into the `ReportDetailPage` and `ActionButtons` components, and improves the user experience by adding toast notifications and confirmation modals for critical actions. It also includes minor updates to localization files for consistency in capitalization.
* Added a `ConfirmationModal` component (`frontend/src/common/components/Modal/ConfirmationModal.tsx`) with customizable title, message, and actions. This component is styled as a bottom sheet and supports dynamic content replacement. [[1]](diffhunk://#diff-d9a6dcce0fec3b6ab37592e1dedfa3bd6874a91f45577e57ac9c619b883587dbR1-R77) [[2]](diffhunk://#diff-b1811ebc1b7d5d66500aaad18043ed93e1ca4556e3cc8cf2834472a022533657R1-R84)
* …

[ADE-67] Discard and Upload new Report functionality

---

backend/src/document-processor/services/aws-bedrock.service.ts
backend/src/services/perplexity.service.ts

fix: enhance medical analysis instructions and enforce metadata integrity
{...}
{...}
{...}

[ADE-66] fix: enhance medical analysis instructions and enforce metadata integrity

---

backend/src/document-processor/services/aws-bedrock.service.ts
backend/src/document-processor/services/document-processor.service.spec.ts
backend/src/document-processor/services/document-processor.service.ts
backend/src/services/perplexity.service.ts

Update critical instructions in PerplexityService to clarify metadata handling
{...}
{...}
{...}

[ADE-208] Update critical instructions in PerplexityService to clarify metadata handling

---

frontend/src/pages/Reports/ReportDetailPage.tsx

This pull request introduces a new `UploadModal` component to the `ReportDetailPage` in the frontend application. The changes include integrating the modal into the page, managing its state, and updating the user flow for uploading new reports.
* **Component Import**: Added the `UploadModal` component import to the `ReportDetailPage` file. (`[frontend/src/pages/Reports/ReportDetailPage.tsxR18](diffhunk://#diff-41d2e46246c1fcacef4f2cb888d10ce2e4087ed69ec7ab0bf5142ec5fe4c3364R18)`)
* **State Management**: Introduced a new state variable `isUploadModalOpen` and a handler function `handleUploadComplete` to manage the modal's visibility and behavior after upload completion. (`[frontend/src/pages/Reports/ReportDetailPage.tsxR40-R45](diffhunk://#diff-41d2e46246c1fcacef4f2cb888d10ce2e4087ed69ec7ab …

[ADE-216] Add UploadModal component and integrate upload handling in ReportDetailPage

---

frontend/src/common/utils/i18n/resources/en/reportDetail.json
frontend/src/pages/Processing/ProcessingPage.scss
frontend/src/pages/Reports/ReportDetailPage.scss
frontend/src/pages/Reports/components/OriginalReportTab.tsx
frontend/src/pages/Reports/components/ReportHeader.tsx

This pull request includes updates to improve the user interface, enhance text presentation, and add a safeguard for accessing optional data. The most important changes include adjustments to the text for empty states, CSS refinements for layout and readability, and a fix to prevent potential runtime errors when accessing `medicalComments`.
* Updated the empty state message in `reportDetail.json` to improve clarity: changed "No values available." to "No values to display." (`frontend/src/common/utils/i18n/resources/en/reportDetail.json`)
* Reduced the `min-width` of test result cells from `160px` to `40px` and added `line-height: 1.4em` for better text wrapping and spacing. (`frontend/src/pages/Reports/ReportDetailPage.scss`)
* Added margins (`margin-left`, `margin-top`, and …

[ADE-203] UI fixes

---

backend/src/services/perplexity.service.ts
frontend/src/common/hooks/useChat.ts
frontend/src/common/hooks/useReports.ts
frontend/src/common/utils/constants.ts
frontend/src/pages/Home/HomePage.tsx
frontend/src/pages/Processing/ProcessingPage.tsx
frontend/src/pages/Reports/ReportDetailPage.tsx
frontend/src/pages/Reports/ReportsListPage.tsx

This pull request introduces several changes to improve code maintainability and consistency, focusing on refactoring query keys into a centralized `QueryKey` enum, updating query-related logic, and enhancing the functionality of report-related features. The most significant changes include replacing hardcoded query keys with `QueryKey` constants, adding a new `useToggleReportBookmark` hook, and updating various components to use these improvements.
* Replaced hardcoded query keys with constants from the new `QueryKey` enum in `frontend/src/common/utils/constants.ts` to ensure consistency and reduce duplication. This affects multiple files, including `useChat.ts`, `useReports.ts`, and several page components. [[1]](diffhunk://#diff-983cebfcbc90fde019a48f3f7104c0fd201eaeaf202fb4d68080915d28 …

[ADE-215] fix stale data in the app

---

frontend/src/common/hooks/useReports.ts
frontend/src/pages/Processing/ProcessingPage.tsx
frontend/src/pages/Processing/components/ProcessingError.tsx

This pull request introduces improvements to the bookmarking functionality, error handling, and user experience in the processing flow. The most notable changes include refactoring the bookmark update logic, ensuring proper cleanup of intervals, and integrating an upload modal in the error handling component.
* Refactored the `useToggleReportBookmark` hook to simplify the logic for updating the bookmark status in the report detail page by directly replacing the report if IDs match, improving code clarity and maintainability. (`frontend/src/common/hooks/useReports.ts`)
* Added a call to `clearStatusCheckInterval()` before starting a new interval in the `ProcessingPage` component to ensure proper cleanup of intervals and prevent potential memory leaks. …

[ADE-215] fixes

---

frontend/src/common/components/Router/TabNavigation.tsx
frontend/src/common/hooks/useReports.ts
frontend/src/common/utils/i18n/resources/en/common.json
frontend/src/common/utils/i18n/resources/en/reportDetail.json
frontend/src/common/utils/i18n/resources/fr/common.json
frontend/src/common/utils/i18n/resources/fr/reportDetail.json
frontend/src/pages/Home/HomePage.tsx
frontend/src/pages/Home/components/ReportItem/ReportItem.tsx
frontend/src/pages/Reports/ReportsListPage.tsx
frontend/src/pages/Reports/components/ActionButtons.tsx

Refactor translation hooks and update i18n resources for improved localization support
{...}
{...}
{...}

[ADE-215] Refactor translation hooks and update i18n resources for improved localization support

---

frontend/package-lock.json
frontend/package.json
frontend/src/common/services/auth/direct-cognito-auth-service.ts

feat: add Cognito Identity client and enhance DirectCognitoAuthService for token management and AWS credentials retrieval

feat: add Cognito Identity client and enhance DirectCognitoAuthService for token management and AWS credentials retrieval

---

frontend/src/common/services/auth/direct-cognito-auth-service.ts
frontend/src/common/utils/i18n/resources/en/common.json

feat: enhance token management by extracting expiration from ID token and improving refresh logic

feat: enhance token management by extracting expiration from ID token and improving refresh logic

---

frontend/src/pages/ReportDetail/components/AiAnalysisTab.tsx

fix: populate normalValues in AiAnalysisTab component
{...}
{...}
{...}

fix: populate normalValues in AiAnalysisTab component

---

frontend/src/common/components/AIAssistant/AIAssistantModal.scss
frontend/src/common/components/AIAssistant/AIAssistantModal.tsx
frontend/src/common/components/Chat/ChatContainer.tsx
frontend/src/common/components/Chat/ChatInput.scss
frontend/src/pages/Chat/ChatPage.tsx

[ADE-200] UI fixes

---

frontend/src/common/i18n/en/auth.json
frontend/src/common/i18n/en/common.json
frontend/src/common/utils/i18n/resources/en/auth.json
frontend/src/common/utils/i18n/resources/es/auth.json
frontend/src/common/utils/i18n/resources/fr/auth.json
frontend/src/pages/Auth/SignUp/components/SignUpForm.scss
frontend/src/pages/Auth/SignUp/components/SignUpForm.tsx
frontend/src/pages/Auth/Verify/VerificationPage.scss
frontend/src/pages/Auth/Verify/VerificationPage.tsx
frontend/src/pages/Auth/Verify/components/VerificationForm.scss
frontend/src/pages/Auth/Verify/components/VerificationForm.tsx

{Describe what kind of change does this PR introduce}
{...}
{...}
{...}

Small improvements to Sign Up page
